### ISSUE TITLE
unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by ClaudiaShu** [jaspreetdhanjan/icp#1]
Hello my friend, thank you for sharing this work,
I've run into a bug when testing the `point to plane` algorithm with your code.
the `correspondence_list.append((closest, normals[closest]))` line shows `unhashable type: 'numpy.ndarray'`
How can I fix that? Thank you very much

**Comment by jaspreetdhanjan** [comment]
Hi! Firstly, thanks so much for using my work!

To be honest, right now I'm not sure. I'll have to do some digging and get back to you. The point to plane stuff is untested because of how the projection/normal map works :)

**Comment by ClaudiaShu** [comment]
Thanks a lot and looking forward to your reply!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
